// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cinemawebapp.Data;

#nullable disable

namespace cinemawebapp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418232306_UpdateMovieSeed")]
    partial class UpdateMovieSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cinemawebapp.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "General Paul Teodorescu Boulevard no. 4, AFI Palace Cotroceni",
                            City = "Bucharest",
                            Contact = "officeafibuc@thefilmvault.ro",
                            ImagePath = "/images/cinema1.jpg",
                            Name = "The Film Vault AFI Palace Cotroceni",
                            OpeningHours = "Mon - Sun 10:00 - 23:00"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Severin Street 61, Promenada Mall",
                            City = "Craiova",
                            Contact = "officepromenadacraiova@thefilmvault.ro",
                            ImagePath = "/images/cinema2.jpg",
                            Name = "The Film Vault Promenada Mall Craiova",
                            OpeningHours = "Mon - Sun 10:30 - 23:00"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandru Vaida Voevod Street 55, Iulius Mall",
                            City = "Cluj-Napoca",
                            Contact = "officecincluj@thefilmvault.ro",
                            ImagePath = "/images/cinema3.jpg",
                            Name = "The Film Vault Cinema City Cluj-Napoca",
                            OpeningHours = "Mon - Sun 10:30 - 23:00"
                        },
                        new
                        {
                            Id = 4,
                            Address = "100 Sagului Street, Shopping City Timisoara",
                            City = "Timisoara",
                            Contact = "officecintim@thefilmvault.ro",
                            ImagePath = "/images/cinema4.jpg",
                            Name = "The Film Vault Cinema City Timisoara",
                            OpeningHours = "Mon - Sun 10:00 - 23:00"
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 120,
                            CinemaId = 1,
                            Name = "Hall 1"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 200,
                            CinemaId = 1,
                            Name = "IMAX"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100,
                            CinemaId = 2,
                            Name = "Hall 1"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 80,
                            CinemaId = 2,
                            Name = "Hall 2"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 150,
                            CinemaId = 3,
                            Name = "Hall 1"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 130,
                            CinemaId = 4,
                            Name = "Hall 1"
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUpcoming")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRating = "13+",
                            Description = "Welcome to a world without rules.\r\nBatman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
                            Director = "Christopher Nolan",
                            DurationMinutes = 152,
                            Genre = "Action / Crime",
                            ImagePath = "/images/negruvoda.jpg",
                            IsUpcoming = false,
                            Title = "The Dark Knight",
                            TrailerUrl = "https://www.youtube.com/embed/EXeTwQWrcwY"
                        },
                        new
                        {
                            Id = 2,
                            AgeRating = "18+",
                            Description = "Gluttony. Greed. Sloth. Envy. Wrath. Pride. Lust.\r\nTwo homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the “seven deadly sins” in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Somerset researches each sin in an effort to get inside the killer’s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.",
                            Director = "David Fincher",
                            DurationMinutes = 127,
                            Genre = "Crime / Thriller",
                            ImagePath = "/images/Se7en.jpg",
                            IsUpcoming = false,
                            Title = "Se7en",
                            TrailerUrl = "https://www.youtube.com/embed/znmZoVkCjpI"
                        },
                        new
                        {
                            Id = 3,
                            AgeRating = "15+",
                            Description = "Music was his passion. Survival was his masterpiece.\r\nThe true story of pianist Władysław Szpilman’s experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.\r\n\r\n",
                            Director = "Roman Polanski",
                            DurationMinutes = 150,
                            Genre = "Drama / War",
                            ImagePath = "/images/ThePianist.jpg",
                            IsUpcoming = false,
                            Title = "The Pianist",
                            TrailerUrl = "https://www.youtube.com/embed/BFwGqLa_oAo"
                        },
                        new
                        {
                            Id = 4,
                            AgeRating = "15+",
                            Description = "Act like you own the place.\r\nAll unemployed, Ki-taek’s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
                            Director = "Bong Joon-ho",
                            DurationMinutes = 132,
                            Genre = "Thriller / Drama",
                            ImagePath = "/images/Parasite.jpg",
                            IsUpcoming = false,
                            Title = "Parasite",
                            TrailerUrl = "https://www.youtube.com/embed/5xH0HfJHsaY"
                        },
                        new
                        {
                            Id = 5,
                            AgeRating = "G",
                            Description = "After 700 years of doing what he was built for, he’ll discover what he was meant for.\r\nAfter hundreds of years doing what he was built for, WALL•E— a robot designed to clean up the earth—discovers a new purpose in life when he meets a sleek search robot named EVE. EVE comes to realize that WALL•E has inadvertently stumbled upon the key to the planet’s future, and races back to space to report to the humans. Meanwhile, WALL•E chases EVE across the galaxy and sets into motion one of the most imaginative adventures ever brought to the big screen.\r\n\r\n",
                            Director = "Andrew Stanton",
                            DurationMinutes = 98,
                            Genre = "Animation / Sci-Fi",
                            ImagePath = "/images/WALL·E.jpg",
                            IsUpcoming = false,
                            Title = "WALL-E",
                            TrailerUrl = "https://www.youtube.com/embed/alIq_wG9FNk"
                        },
                        new
                        {
                            Id = 6,
                            AgeRating = "G",
                            Description = "Ahhh… it’s got that new movie smell.\r\nLightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town’s offbeat characters.\r\n\r\n",
                            Director = "John Lasseter",
                            DurationMinutes = 116,
                            Genre = "Animation / Comedy",
                            ImagePath = "/images/Cars.jpg",
                            IsUpcoming = false,
                            Title = "Cars",
                            TrailerUrl = "https://www.youtube.com/embed/9XCB6GGc3s0"
                        },
                        new
                        {
                            Id = 7,
                            AgeRating = "18+",
                            Description = "On every street in every city in this country, there’s a nobody who dreams of being somebody. He’s a lonely forgotten man desperate to prove that he’s alive.\r\nSuffering from insomnia, disturbed loner Travis Bickle takes a job as a New York City cabbie, haunting the streets nightly, growing increasingly detached from reality as he dreams of cleaning up the filthy city.\r\n\r\n",
                            Director = "Martin Scorsese",
                            DurationMinutes = 114,
                            Genre = "Crime / Drama",
                            ImagePath = "/images/TaxiDriver.jpg",
                            IsUpcoming = false,
                            Title = "Taxi Driver",
                            TrailerUrl = "https://www.youtube.com/embed/UUxbBMkOoM8"
                        },
                        new
                        {
                            Id = 8,
                            AgeRating = "15+",
                            Description = "Innocence has a power evil cannot imagine.\r\nIn post–civil war Spain, 10-year-old Ofelia moves with her pregnant mother to live under the control of her cruel stepfather. Drawn into a mysterious labyrinth, she meets a faun who reveals that she may be a lost princess from an underground kingdom. To return to her true father, she must complete a series of surreal and perilous tasks that blur the line between reality and fantasy.\r\n\r\n",
                            Director = "Guillermo del Toro",
                            DurationMinutes = 118,
                            Genre = "Fantasy / Drama",
                            ImagePath = "/images/Pan’sLabyrinth.jpg",
                            IsUpcoming = false,
                            Title = "Pan's Labyrinth",
                            TrailerUrl = "https://www.youtube.com/embed/sRTsJITq2EY"
                        },
                        new
                        {
                            Id = 9,
                            AgeRating = "15+",
                            Description = "Fear can hold you prisoner. Hope can set you free.\r\nImprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates – including an older prisoner named Red – for his integrity and unquenchable sense of hope.\r\n\r\n",
                            Director = "Frank Darabont",
                            DurationMinutes = 142,
                            Genre = "Drama",
                            ImagePath = "/images/TheShawshankRedemption.jpg",
                            IsUpcoming = true,
                            Title = "The Shawshank Redemption",
                            TrailerUrl = "https://www.youtube.com/embed/NmzuHjWmXOc"
                        },
                        new
                        {
                            Id = 10,
                            AgeRating = "15+",
                            Description = "Whoever saves one life, saves the world entire.\r\nThe true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.\r\n\r\n",
                            Director = "Steven Spielberg",
                            DurationMinutes = 195,
                            Genre = "Drama / History",
                            ImagePath = "/images/Schindler’sList.jpg",
                            IsUpcoming = true,
                            Title = "Schindler's List",
                            TrailerUrl = "https://www.youtube.com/embed/gG22M1L6G4Q"
                        },
                        new
                        {
                            Id = 11,
                            AgeRating = "18+",
                            Description = "Mischief. Mayhem. Soap.\r\nA ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground “fight clubs” forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.\r\n\r\n",
                            Director = "David Fincher",
                            DurationMinutes = 139,
                            Genre = "Drama / Thriller",
                            ImagePath = "/images/FightClub.jpg",
                            IsUpcoming = true,
                            Title = "Fight Club",
                            TrailerUrl = "https://www.youtube.com/embed/SUXWAEX2jlg"
                        },
                        new
                        {
                            Id = 12,
                            AgeRating = "12+",
                            Description = "Mankind was born on Earth. It was never meant to die here.\r\nThe adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.\r\n\r\n",
                            Director = "Christopher Nolan",
                            DurationMinutes = 169,
                            Genre = "Sci-Fi / Adventure",
                            ImagePath = "/images/Interstellar.jpg",
                            IsUpcoming = true,
                            Title = "Interstellar",
                            TrailerUrl = "https://www.youtube.com/embed/zSWdZVtXT7E"
                        },
                        new
                        {
                            Id = 13,
                            AgeRating = "18+",
                            Description = "To enter the mind of a killer she must challenge the mind of a madman.\r\nClarice Starling is a top student at the FBI’s training academy. Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism. Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.\r\n\r\n",
                            Director = "Jonathan Demme",
                            DurationMinutes = 118,
                            Genre = "Crime / Thriller",
                            ImagePath = "/images/TheSilenceoftheLambs.jpg",
                            IsUpcoming = true,
                            Title = "The Silence of the Lambs",
                            TrailerUrl = "https://www.youtube.com/embed/W6Mm8Sbe__o"
                        },
                        new
                        {
                            Id = 14,
                            AgeRating = "15+",
                            Description = "Time is the enemy.\r\nAt the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.\r\n\r\n",
                            Director = "Sam Mendes",
                            DurationMinutes = 119,
                            Genre = "War / Drama",
                            ImagePath = "/images/1917.jpg",
                            IsUpcoming = true,
                            Title = "1917",
                            TrailerUrl = "https://www.youtube.com/embed/YqNYrYUiMfg"
                        },
                        new
                        {
                            Id = 15,
                            AgeRating = "15+",
                            Description = "The mission is a man.\r\nAs U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.\r\n\r\n",
                            Director = "Steven Spielberg",
                            DurationMinutes = 169,
                            Genre = "War / Drama",
                            ImagePath = "/images/SavingPrivateRyan.jpg",
                            IsUpcoming = true,
                            Title = "Saving Private Ryan",
                            TrailerUrl = "https://www.youtube.com/embed/zwhP5b4tD6g"
                        },
                        new
                        {
                            Id = 16,
                            AgeRating = "15+",
                            Description = "The event the world will never forget.\r\nIn 1947, four German judges who served on the bench during the Nazi regime face a military tribunal to answer charges of crimes against humanity. Chief Justice Haywood hears evidence and testimony not only from lead defendant Ernst Janning and his defense attorney Hans Rolfe, but also from the widow of a Nazi general, an idealistic U.S. Army captain and reluctant witness Irene Wallner.\r\n\r\n",
                            Director = "Stanley Kramer",
                            DurationMinutes = 186,
                            Genre = "Drama / History",
                            ImagePath = "/images/JudgmentatNuremberg.jpg",
                            IsUpcoming = true,
                            Title = "Judgment at Nuremberg",
                            TrailerUrl = "https://www.youtube.com/embed/kovL8QOS408"
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "20% off with a valid student ID. Available for all screenings, every day.",
                            DiscountPercent = 20m,
                            Emoji = "🎓",
                            IsActive = true,
                            Title = "Student Discount",
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidUntil = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Free admission every Monday for veterans and senior citizens aged 65+.",
                            DiscountPercent = 100m,
                            Emoji = "🎖️",
                            IsActive = true,
                            Title = "Veterans Monday",
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidUntil = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Buy 3 tickets, get the 4th free. Valid Saturday & Sunday only.",
                            DiscountPercent = 25m,
                            Emoji = "👨‍👩‍👧‍👦",
                            IsActive = true,
                            Title = "Weekend Family Pack",
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidUntil = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HallId = 1,
                            MovieId = 1,
                            StartTime = new DateTime(2025, 5, 10, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            HallId = 2,
                            MovieId = 1,
                            StartTime = new DateTime(2025, 5, 10, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            HallId = 3,
                            MovieId = 2,
                            StartTime = new DateTime(2025, 5, 11, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            HallId = 5,
                            MovieId = 3,
                            StartTime = new DateTime(2025, 5, 12, 17, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            HallId = 6,
                            MovieId = 2,
                            StartTime = new DateTime(2025, 5, 13, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScreeningId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 35m,
                            PurchasedAt = new DateTime(2025, 5, 9, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ScreeningId = 1,
                            SeatNumber = "A1",
                            TicketType = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            Price = 28m,
                            PurchasedAt = new DateTime(2025, 5, 9, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            ScreeningId = 1,
                            SeatNumber = "A2",
                            TicketType = "Student"
                        },
                        new
                        {
                            Id = 3,
                            Price = 25m,
                            PurchasedAt = new DateTime(2025, 5, 9, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ScreeningId = 2,
                            SeatNumber = "B5",
                            TicketType = "Senior"
                        },
                        new
                        {
                            Id = 4,
                            Price = 35m,
                            PurchasedAt = new DateTime(2025, 5, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ScreeningId = 3,
                            SeatNumber = "C3",
                            TicketType = "Standard"
                        },
                        new
                        {
                            Id = 5,
                            Price = 35m,
                            PurchasedAt = new DateTime(2025, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ScreeningId = 4,
                            SeatNumber = "D7",
                            TicketType = "Standard"
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Hall", b =>
                {
                    b.HasOne("cinemawebapp.Models.Cinema", "Cinema")
                        .WithMany("Halls")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("cinemawebapp.Models.Screening", b =>
                {
                    b.HasOne("cinemawebapp.Models.Hall", "Hall")
                        .WithMany("Screenings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cinemawebapp.Models.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("cinemawebapp.Models.Ticket", b =>
                {
                    b.HasOne("cinemawebapp.Models.Screening", "Screening")
                        .WithMany("Tickets")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screening");
                });

            modelBuilder.Entity("cinemawebapp.Models.Cinema", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("cinemawebapp.Models.Hall", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("cinemawebapp.Models.Movie", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("cinemawebapp.Models.Screening", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
