// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cinemawebapp.Data;

#nullable disable

namespace cinemawebapp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418225304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cinemawebapp.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "General Paul Teodorescu Boulevard no. 4, AFI Palace Cotroceni",
                            City = "Bucharest",
                            Contact = "officeafibuc@thefilmvault.ro",
                            ImagePath = "/images/cinema1.jpg",
                            Name = "The Film Vault AFI Palace Cotroceni",
                            OpeningHours = "Mon - Sun 10:00 - 23:00"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Severin Street 61, Promenada Mall",
                            City = "Craiova",
                            Contact = "officepromenadacraiova@thefilmvault.ro",
                            ImagePath = "/images/cinema2.jpg",
                            Name = "The Film Vault Promenada Mall Craiova",
                            OpeningHours = "Mon - Sun 10:30 - 23:00"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandru Vaida Voevod Street 55, Iulius Mall",
                            City = "Cluj-Napoca",
                            Contact = "officecincluj@thefilmvault.ro",
                            ImagePath = "/images/cinema3.jpg",
                            Name = "The Film Vault Cinema City Cluj-Napoca",
                            OpeningHours = "Mon - Sun 10:30 - 23:00"
                        },
                        new
                        {
                            Id = 4,
                            Address = "100 Sagului Street, Shopping City Timisoara",
                            City = "Timisoara",
                            Contact = "officecintim@thefilmvault.ro",
                            ImagePath = "/images/cinema4.jpg",
                            Name = "The Film Vault Cinema City Timisoara",
                            OpeningHours = "Mon - Sun 10:00 - 23:00"
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 120,
                            CinemaId = 1,
                            Name = "Hall 1"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 200,
                            CinemaId = 1,
                            Name = "IMAX"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 100,
                            CinemaId = 2,
                            Name = "Hall 1"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 80,
                            CinemaId = 2,
                            Name = "Hall 2"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 150,
                            CinemaId = 3,
                            Name = "Hall 1"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 130,
                            CinemaId = 4,
                            Name = "Hall 1"
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUpcoming")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRating = "13+",
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Director = "Christopher Nolan",
                            DurationMinutes = 152,
                            Genre = "Action / Crime",
                            ImagePath = "/images/negruvoda.jpg",
                            IsUpcoming = false,
                            Title = "The Dark Knight",
                            TrailerUrl = "https://www.youtube.com/embed/EXeTwQWrcwY"
                        },
                        new
                        {
                            Id = 2,
                            AgeRating = "18+",
                            Description = "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
                            Director = "David Fincher",
                            DurationMinutes = 127,
                            Genre = "Crime / Thriller",
                            ImagePath = "/images/Se7en.jpg",
                            IsUpcoming = false,
                            Title = "Se7en",
                            TrailerUrl = "https://www.youtube.com/embed/znmZoVkCjpI"
                        },
                        new
                        {
                            Id = 3,
                            AgeRating = "15+",
                            Description = "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
                            Director = "Roman Polanski",
                            DurationMinutes = 150,
                            Genre = "Drama / War",
                            ImagePath = "/images/ThePianist.jpg",
                            IsUpcoming = false,
                            Title = "The Pianist",
                            TrailerUrl = "https://www.youtube.com/embed/BFwGqLa_oAo"
                        },
                        new
                        {
                            Id = 4,
                            AgeRating = "15+",
                            Description = "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
                            Director = "Bong Joon-ho",
                            DurationMinutes = 132,
                            Genre = "Thriller / Drama",
                            ImagePath = "/images/Parasite.jpg",
                            IsUpcoming = false,
                            Title = "Parasite",
                            TrailerUrl = "https://www.youtube.com/embed/5xH0HfJHsaY"
                        },
                        new
                        {
                            Id = 5,
                            AgeRating = "G",
                            Description = "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
                            Director = "Andrew Stanton",
                            DurationMinutes = 98,
                            Genre = "Animation / Sci-Fi",
                            ImagePath = "/images/WALL·E.jpg",
                            IsUpcoming = false,
                            Title = "WALL-E",
                            TrailerUrl = "https://www.youtube.com/embed/alIq_wG9FNk"
                        },
                        new
                        {
                            Id = 6,
                            AgeRating = "G",
                            Description = "A hotshot race-car named Lightning McQueen gets waylaid in Radiator Springs, where he finds the true meaning of friendship and family.",
                            Director = "John Lasseter",
                            DurationMinutes = 116,
                            Genre = "Animation / Comedy",
                            ImagePath = "/images/Cars.jpg",
                            IsUpcoming = false,
                            Title = "Cars",
                            TrailerUrl = "https://www.youtube.com/embed/9XCB6GGc3s0"
                        },
                        new
                        {
                            Id = 7,
                            AgeRating = "18+",
                            Description = "A mentally unstable veteran works as a nighttime taxi driver in New York City, where the streets are filled with corruption, and he dreams of cleaning up the city.",
                            Director = "Martin Scorsese",
                            DurationMinutes = 114,
                            Genre = "Crime / Drama",
                            ImagePath = "/images/TaxiDriver.jpg",
                            IsUpcoming = false,
                            Title = "Taxi Driver",
                            TrailerUrl = "https://www.youtube.com/embed/UUxbBMkOoM8"
                        },
                        new
                        {
                            Id = 8,
                            AgeRating = "15+",
                            Description = "In post-Civil War Spain, a young girl escapes into a fantastical labyrinth ruled by a mysterious faun, while the world around her grows darker.",
                            Director = "Guillermo del Toro",
                            DurationMinutes = 118,
                            Genre = "Fantasy / Drama",
                            ImagePath = "/images/Pan'sLabyrinth.jpg",
                            IsUpcoming = false,
                            Title = "Pan's Labyrinth",
                            TrailerUrl = "https://www.youtube.com/embed/sRTsJITq2EY"
                        },
                        new
                        {
                            Id = 9,
                            AgeRating = "15+",
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Director = "Frank Darabont",
                            DurationMinutes = 142,
                            Genre = "Drama",
                            ImagePath = "/images/TheShawshankRedemption.jpg",
                            IsUpcoming = true,
                            Title = "The Shawshank Redemption",
                            TrailerUrl = "https://www.youtube.com/embed/NmzuHjWmXOc"
                        },
                        new
                        {
                            Id = 10,
                            AgeRating = "15+",
                            Description = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            Director = "Steven Spielberg",
                            DurationMinutes = 195,
                            Genre = "Drama / History",
                            ImagePath = "/images/Schindler'sList.jpg",
                            IsUpcoming = true,
                            Title = "Schindler's List",
                            TrailerUrl = "https://www.youtube.com/embed/gG22M1L6G4Q"
                        },
                        new
                        {
                            Id = 11,
                            AgeRating = "18+",
                            Description = "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.",
                            Director = "David Fincher",
                            DurationMinutes = 139,
                            Genre = "Drama / Thriller",
                            ImagePath = "/images/FightClub.jpg",
                            IsUpcoming = true,
                            Title = "Fight Club",
                            TrailerUrl = "https://www.youtube.com/embed/SUXWAEX2jlg"
                        },
                        new
                        {
                            Id = 12,
                            AgeRating = "12+",
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Director = "Christopher Nolan",
                            DurationMinutes = 169,
                            Genre = "Sci-Fi / Adventure",
                            ImagePath = "/images/Interstellar.jpg",
                            IsUpcoming = true,
                            Title = "Interstellar",
                            TrailerUrl = "https://www.youtube.com/embed/zSWdZVtXT7E"
                        },
                        new
                        {
                            Id = 13,
                            AgeRating = "18+",
                            Description = "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.",
                            Director = "Jonathan Demme",
                            DurationMinutes = 118,
                            Genre = "Crime / Thriller",
                            ImagePath = "/images/TheSilenceoftheLambs.jpg",
                            IsUpcoming = true,
                            Title = "The Silence of the Lambs",
                            TrailerUrl = "https://www.youtube.com/embed/W6Mm8Sbe__o"
                        },
                        new
                        {
                            Id = 14,
                            AgeRating = "15+",
                            Description = "Two British soldiers are sent on a suicide mission through enemy territory to deliver a message that could save 1,600 of their comrades.",
                            Director = "Sam Mendes",
                            DurationMinutes = 119,
                            Genre = "War / Drama",
                            ImagePath = "/images/1917.jpg",
                            IsUpcoming = true,
                            Title = "1917",
                            TrailerUrl = "https://www.youtube.com/embed/YqNYrYUiMfg"
                        },
                        new
                        {
                            Id = 15,
                            AgeRating = "15+",
                            Description = "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
                            Director = "Steven Spielberg",
                            DurationMinutes = 169,
                            Genre = "War / Drama",
                            ImagePath = "/images/SavingPrivateRyan.jpg",
                            IsUpcoming = true,
                            Title = "Saving Private Ryan",
                            TrailerUrl = "https://www.youtube.com/embed/zwhP5b4tD6g"
                        },
                        new
                        {
                            Id = 16,
                            AgeRating = "15+",
                            Description = "In 1948, an American judge presides over the trial of four Nazi judges who served on the bench during the Third Reich.",
                            Director = "Stanley Kramer",
                            DurationMinutes = 186,
                            Genre = "Drama / History",
                            ImagePath = "/images/JudgmentatNuremberg.jpg",
                            IsUpcoming = true,
                            Title = "Judgment at Nuremberg",
                            TrailerUrl = "https://www.youtube.com/embed/kovL8QOS408"
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "20% off with a valid student ID. Available for all screenings, every day.",
                            DiscountPercent = 20m,
                            Emoji = "🎓",
                            IsActive = true,
                            Title = "Student Discount",
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidUntil = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Free admission every Monday for veterans and senior citizens aged 65+.",
                            DiscountPercent = 100m,
                            Emoji = "🎖️",
                            IsActive = true,
                            Title = "Veterans Monday",
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidUntil = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Buy 3 tickets, get the 4th free. Valid Saturday & Sunday only.",
                            DiscountPercent = 25m,
                            Emoji = "👨‍👩‍👧‍👦",
                            IsActive = true,
                            Title = "Weekend Family Pack",
                            ValidFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidUntil = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HallId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("MovieId");

                    b.ToTable("Screenings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HallId = 1,
                            MovieId = 1,
                            StartTime = new DateTime(2025, 5, 10, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            HallId = 2,
                            MovieId = 1,
                            StartTime = new DateTime(2025, 5, 10, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            HallId = 3,
                            MovieId = 2,
                            StartTime = new DateTime(2025, 5, 11, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            HallId = 5,
                            MovieId = 3,
                            StartTime = new DateTime(2025, 5, 12, 17, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            HallId = 6,
                            MovieId = 2,
                            StartTime = new DateTime(2025, 5, 13, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScreeningId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 35m,
                            PurchasedAt = new DateTime(2025, 5, 9, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ScreeningId = 1,
                            SeatNumber = "A1",
                            TicketType = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            Price = 28m,
                            PurchasedAt = new DateTime(2025, 5, 9, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            ScreeningId = 1,
                            SeatNumber = "A2",
                            TicketType = "Student"
                        },
                        new
                        {
                            Id = 3,
                            Price = 25m,
                            PurchasedAt = new DateTime(2025, 5, 9, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ScreeningId = 2,
                            SeatNumber = "B5",
                            TicketType = "Senior"
                        },
                        new
                        {
                            Id = 4,
                            Price = 35m,
                            PurchasedAt = new DateTime(2025, 5, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ScreeningId = 3,
                            SeatNumber = "C3",
                            TicketType = "Standard"
                        },
                        new
                        {
                            Id = 5,
                            Price = 35m,
                            PurchasedAt = new DateTime(2025, 5, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ScreeningId = 4,
                            SeatNumber = "D7",
                            TicketType = "Standard"
                        });
                });

            modelBuilder.Entity("cinemawebapp.Models.Hall", b =>
                {
                    b.HasOne("cinemawebapp.Models.Cinema", "Cinema")
                        .WithMany("Halls")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("cinemawebapp.Models.Screening", b =>
                {
                    b.HasOne("cinemawebapp.Models.Hall", "Hall")
                        .WithMany("Screenings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("cinemawebapp.Models.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("cinemawebapp.Models.Ticket", b =>
                {
                    b.HasOne("cinemawebapp.Models.Screening", "Screening")
                        .WithMany("Tickets")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screening");
                });

            modelBuilder.Entity("cinemawebapp.Models.Cinema", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("cinemawebapp.Models.Hall", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("cinemawebapp.Models.Movie", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("cinemawebapp.Models.Screening", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
